name: honeymarker-integration-action
on:
  push:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  integration:
    name: honeymarker-integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create honeymarker
        uses: ./
        with:
          apikey: ${{ secrets.BUILDEVENTS_APIKEY }}
          dataset: honeymarker-test
          # url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
